version: "3.7"
services:
  cc_backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      GIT_PROJECTS_FOLDER: /projects
    volumes:
      - "./projects1:/projects"
  cc_frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
